'use client';

/**
 * Public biometric enrollment page — no login required.
 * Opened via a magic link generated by an admin.
 * Handles fingerprint (WebAuthn), face, or both depending on the token type.
 */

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { graphqlRequest } from '@/lib/graphql';
import {
  captureFrame, isWebAuthnAvailable,
  runWebAuthnRegistration, startCamera, stopCamera,
} from '@/lib/webauthn';
import { AlertCircle, Camera, CheckCircle, Fingerprint, Loader2 } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';

// ---------------------------------------------------------------------------
// GraphQL — no auth token needed for these
// ---------------------------------------------------------------------------
const RESOLVE_TOKEN = `
  query ResolveToken($token: String!) {
    resolveEnrollmentToken(token: $token) {
      valid message token userId userName enrollmentType expiresAt
    }
  }
`;

const WEBAUTHN_BEGIN = `
  mutation BeginReg($userId: ID!) {
    webauthnBeginRegister(userId: $userId)
  }
`;

const ENROLL_FINGERPRINT = `
  mutation EnrollFP($token: String!, $credentialJson: String!) {
    enrollFingerprintWithToken(token: $token, credentialJson: $credentialJson)
  }
`;

const ENROLL_FACE = `
  mutation EnrollFace($token: String!, $imageBase64: String!) {
    enrollFaceWithToken(token: $token, imageBase64: $imageBase64)
  }
`;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface TokenInfo {
  valid: boolean;
  message: string;
  token: string;
  userId: string;
  userName: string;
  enrollmentType: 'fingerprint' | 'face' | 'both';
  expiresAt: string;
}

type StepStatus = 'idle' | 'working' | 'done' | 'error';

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------
export default function EnrollPage() {
  const { token } = useParams<{ token: string }>();

  const [loading, setLoading] = useState(true);
  const [info, setInfo] = useState<TokenInfo | null>(null);
  const [invalid, setInvalid] = useState('');
  const [webAuthnAvailable, setWebAuthnAvailable] = useState(false);

  // Fingerprint state
  const [fpStatus, setFpStatus] = useState<StepStatus>('idle');
  const [fpMsg, setFpMsg] = useState('');
  const [fpDone, setFpDone] = useState(false);

  // Face state
  const [faceStatus, setFaceStatus] = useState<StepStatus>('idle');
  const [faceMsg, setFaceMsg] = useState('');
  const [faceDone, setFaceDone] = useState(false);
  const [cameraOpen, setCameraOpen] = useState(false);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Resolve the token on mount
  useEffect(() => {
    if (!token) return;
    Promise.all([
      graphqlRequest<any>({ query: RESOLVE_TOKEN, variables: { token } }),
      isWebAuthnAvailable(),
    ]).then(([res, avail]) => {
      const data = res.data?.resolveEnrollmentToken;
      if (!data?.valid) {
        setInvalid(data?.message ?? 'Invalid link');
      } else {
        setInfo(data as TokenInfo);
      }
      setWebAuthnAvailable(avail);
    }).catch(() => setInvalid('Failed to load — check your connection'))
      .finally(() => setLoading(false));
  }, [token]);

  // Camera lifecycle
  useEffect(() => {
    if (!cameraOpen) { stopCamera(stream); setStream(null); return; }
    if (!videoRef.current) return;
    startCamera(videoRef.current, 'user')
      .then(s => setStream(s))
      .catch(() => { setFaceMsg('Cannot access camera'); setFaceStatus('error'); setCameraOpen(false); });
  }, [cameraOpen]);

  // ── Fingerprint registration ──────────────────────────────────────────
  async function handleFingerprint() {
    if (!info || fpStatus === 'working') return;
    setFpStatus('working'); setFpMsg('');
    try {
      // Step 1: get challenge
      const r1 = await graphqlRequest<any>({ query: WEBAUTHN_BEGIN, variables: { userId: info.userId } });
      const optionsJson: string = r1.data?.webauthnBeginRegister;

      // Step 2: browser prompts fingerprint sensor on THIS device
      setFpMsg('Follow the prompt on your device…');
      const credentialJson = await runWebAuthnRegistration(optionsJson);

      // Step 3: verify on backend using token (no auth header)
      const r2 = await graphqlRequest<any>({
        query: ENROLL_FINGERPRINT,
        variables: { token: info.token, credentialJson },
      });
      const result = JSON.parse(r2.data?.enrollFingerprintWithToken ?? '{}');
      setFpMsg(result.message);
      if (result.success) { setFpStatus('done'); setFpDone(true); }
      else setFpStatus('error');
    } catch (e: any) {
      setFpMsg(e?.name === 'NotAllowedError' ? 'Fingerprint scan cancelled — try again' : (e?.message ?? 'Failed'));
      setFpStatus('error');
    }
  }

  // ── Face registration ─────────────────────────────────────────────────
  async function handleFaceCapture() {
    if (!videoRef.current || !info || faceStatus === 'working') return;
    setFaceStatus('working'); setFaceMsg('');
    try {
      const imageBase64 = captureFrame(videoRef.current);
      const r = await graphqlRequest<any>({
        query: ENROLL_FACE,
        variables: { token: info.token, imageBase64 },
      });
      const result = JSON.parse(r.data?.enrollFaceWithToken ?? '{}');
      setFaceMsg(result.message);
      if (result.success) { setFaceStatus('done'); setFaceDone(true); setCameraOpen(false); }
      else setFaceStatus('error');
    } catch { setFaceMsg('Network error'); setFaceStatus('error'); }
  }

  const allDone =
    info?.enrollmentType === 'fingerprint' ? fpDone
    : info?.enrollmentType === 'face' ? faceDone
    : fpDone && faceDone;

  // ── Render ─────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (invalid) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="w-full max-w-sm text-center">
          <CardContent className="pt-8 pb-8 space-y-3">
            <AlertCircle className="h-12 w-12 text-red-400 mx-auto" />
            <p className="font-semibold text-lg">Link Invalid</p>
            <p className="text-sm text-muted-foreground">{invalid}</p>
            <p className="text-xs text-muted-foreground">Ask your admin to generate a new enrollment link.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <div className="w-full max-w-sm space-y-4">

        {/* Header */}
        <div className="text-center space-y-1">
          <p className="text-xs text-muted-foreground uppercase tracking-wider">SIMS Biometric Enrollment</p>
          <h1 className="text-2xl font-bold">{info!.userName}</h1>
          <p className="text-sm text-muted-foreground">
            {info!.enrollmentType === 'both' ? 'Register fingerprint and face'
             : info!.enrollmentType === 'fingerprint' ? 'Register fingerprint'
             : 'Register face photo'}
          </p>
        </div>

        {/* All done */}
        {allDone && (
          <Card className="border-green-300 bg-green-50">
            <CardContent className="pt-6 pb-6 text-center space-y-2">
              <CheckCircle className="h-10 w-10 text-green-600 mx-auto" />
              <p className="font-semibold text-green-800">Enrollment complete!</p>
              <p className="text-sm text-green-700">You can close this page.</p>
            </CardContent>
          </Card>
        )}

        {/* ── Fingerprint card ── */}
        {(info!.enrollmentType === 'fingerprint' || info!.enrollmentType === 'both') && !allDone && (
          <Card className={fpDone ? 'border-green-300' : ''}>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Fingerprint className={`h-5 w-5 ${fpDone ? 'text-green-600' : 'text-primary'}`} />
                Fingerprint
                {fpDone && <CheckCircle className="h-4 w-4 text-green-600 ml-auto" />}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {!fpDone && (
                <>
                  {!webAuthnAvailable ? (
                    <p className="text-sm text-amber-600">
                      Fingerprint sensor not detected on this device. Open this link on your phone.
                    </p>
                  ) : (
                    <p className="text-sm text-muted-foreground">
                      Tap the button below. Your device will ask you to place your finger on the sensor.
                    </p>
                  )}
                  {fpMsg && (
                    <p className={`text-sm flex items-center gap-1.5 ${fpStatus === 'error' ? 'text-red-600' : 'text-muted-foreground'}`}>
                      {fpStatus === 'error' && <AlertCircle className="h-4 w-4" />}
                      {fpMsg}
                    </p>
                  )}
                  <Button
                    className="w-full"
                    disabled={fpStatus === 'working' || !webAuthnAvailable}
                    onClick={handleFingerprint}
                  >
                    {fpStatus === 'working'
                      ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Waiting for fingerprint…</>
                      : <><Fingerprint className="h-4 w-4 mr-2" />Register Fingerprint</>
                    }
                  </Button>
                </>
              )}
              {fpDone && <p className="text-sm text-green-700 font-medium">Fingerprint registered successfully!</p>}
            </CardContent>
          </Card>
        )}

        {/* ── Face card ── */}
        {(info!.enrollmentType === 'face' || info!.enrollmentType === 'both') && !allDone && (
          <Card className={faceDone ? 'border-green-300' : ''}>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Camera className={`h-5 w-5 ${faceDone ? 'text-green-600' : 'text-primary'}`} />
                Face Photo
                {faceDone && <CheckCircle className="h-4 w-4 text-green-600 ml-auto" />}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {!faceDone && (
                <>
                  {!cameraOpen ? (
                    <>
                      <p className="text-sm text-muted-foreground">
                        Look directly at the camera and click Open Camera, then Capture.
                      </p>
                      <Button className="w-full" variant="secondary" onClick={() => setCameraOpen(true)}>
                        <Camera className="h-4 w-4 mr-2" />Open Camera
                      </Button>
                    </>
                  ) : (
                    <>
                      <div className="relative rounded-lg overflow-hidden bg-black aspect-video">
                        <video ref={videoRef} className="w-full h-full object-cover" autoPlay muted playsInline />
                        {faceStatus === 'working' && (
                          <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                            <span className="text-white text-sm animate-pulse">Processing…</span>
                          </div>
                        )}
                      </div>
                      {faceMsg && (
                        <p className={`text-sm flex items-center gap-1.5 ${faceStatus === 'error' ? 'text-red-600' : 'text-green-700'}`}>
                          {faceStatus === 'error' ? <AlertCircle className="h-4 w-4" /> : <CheckCircle className="h-4 w-4" />}
                          {faceMsg}
                        </p>
                      )}
                      <div className="flex gap-2">
                        <Button className="flex-1" disabled={faceStatus === 'working'} onClick={handleFaceCapture}>
                          <Camera className="h-4 w-4 mr-2" />
                          {faceStatus === 'working' ? 'Processing…' : 'Capture Photo'}
                        </Button>
                        <Button variant="outline" onClick={() => setCameraOpen(false)}>Cancel</Button>
                      </div>
                    </>
                  )}
                </>
              )}
              {faceDone && <p className="text-sm text-green-700 font-medium">Face photo registered successfully!</p>}
            </CardContent>
          </Card>
        )}

        <p className="text-center text-xs text-muted-foreground">
          Link expires {new Date(info!.expiresAt).toLocaleString()}
        </p>
      </div>
    </div>
  );
}
